### ISSUE TITLE
Write model(elements) broken in version 0.2.0

### ISSUE THREAD

**Issue by LisaWeijers** [Deltares/HYDROLIB-core#195]
**Describe the bug**
I just upgraded to 0.2.0 because I needed to alter the friction in my model and export the new model. However using `fm.save(outputdir) ` now results in a `PermissionError: [Errno 13] Permission denied: 'c:/dhydro/20211102_Developers_tutorial_Hydrolib/code/output/moergestels_broek.mdu'`

**To Reproduce**
With hydrolib-core 0.2.0:
```
from pathlib import Path
from hydrolib.core.io.dimr.models import DIMR, FMComponent
from hydrolib.core.io.mdu.models import FMModel

# Specify paths
root = Path.cwd()
inputdir = root / "data"
modeldir = inputdir / "model"
mdufile = "moergestels_broek.mdu"

# Read mdu model
fm = FMModel(modeldir / mdufile)

# export mdu model
outputdir = root / "output"
fm.save(outputdir)
```

**Expected behavior**
I expect that the (unchanged) fm model would be exported to outputdir. Instead I get:
`PermissionError: [Errno 13] Permission denied: 'c:/dhydro/20211102_Developers_tutorial_Hydrolib/code/output/moergestels_broek.mdu'`

I tried the exact same in another environment where I had hydrolib-core version 0.1.5 and it worked without any problem. That's why I think it is some problem that occurs since the 0.2.0 release. 

**Screenshots**
Full output of error (slightly different export path, but same code that causes the issue)
```
Traceback (most recent call last):
  File "C:\Users\908367\.conda\envs\hydrolib\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\908367\.conda\envs\hydrolib\lib\site-packages\hydrolib\core\basemodel.py", line 452, in file_load_context
    yield file_loading_context
  File "C:\Users\908367\.conda\envs\hydrolib\lib\site-packages\hydrolib\core\basemodel.py", line 640, in save
    self._save_instance()
  File "C:\Users\908367\.conda\envs\hydrolib\lib\site-packages\hydrolib\core\basemodel.py", line 646, in _save_instance
    self._save()
  File "C:\Users\908367\.conda\envs\hydrolib\lib\site-packages\hydrolib\core\basemodel.py", line 691, in _save
    self._serialize(self.dict())
  File "C:\Users\908367\.conda\envs\hydrolib\lib\site-packages\hydrolib\core\io\ini\models.py", line 185, in _serialize
    write_ini(self._resolved_filepath, self._to_document(), config=config)
  File "C:\Users\908367\.conda\envs\hydrolib\lib\site-packages\hydrolib\core\io\ini\serializer.py", line 300, in write_ini
    with path.open("wb") as f:
  File "C:\Users\908367\.conda\envs\hydrolib\lib\pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "C:\Users\908367\.conda\envs\hydrolib\lib\pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
PermissionError: [Errno 13] Permission denied: 'C:\\Dev\\Hydrolib_optimizer\\playground\\export'
```
**Version info (please complete the following information):**
 - OS: Windows 10
 - Version: Hydrolib-core 0.2.0
-  Python version: 3.8.12

**Additional context**
--

**Comment by arthurvd** [comment]
Hi @LisaWeijers,

the above *could* be due to a behavioral change of the `save()` function in the 0.2.0 release. So you retry after making the suggested code change below?

In earlier version, the first argument to the `save()` function was a folder.
Now, it is a filepath (so, including the mdu filename). More info on:
https://deltares.github.io/HYDROLIB-core/0.2.0/reference/api/#hydrolib.core.basemodel.FileModel.is_file_link

Your "PermissionError" is probably due to the OS attempting to create an (mdu) file named "C:\Dev\Hydrolib_optimizer\playground\export", whereas it is already a directory (which is intended).

Does this work for you?:
```python
fm.save(outputdir / mdufile, recurse = True)
```

Saving nested model files is subtle business, if you want to know more about our considerations there, check out this background read:
https://deltares.github.io/HYDROLIB-core/0.2.0/topics/loadsave/

**Comment by LisaWeijers** [comment]
@arthurvd  Ah thanks, that works! 
I guess I got a bit too enthusiastic and didn't notice this subtle change ;)
