### ISSUE TITLE
Implement the use of "launch binder"

### ISSUE THREAD

**Issue by rhutten** [Deltares/HYDROLIB-core#250]
**What is the need for this task.**
The HYDROLIB team strives to create tutorials, which can be executed through binder. 

**What is the task?**
- create environment.yml or use dockerfile
- make launch buttons at each notebook and at the introduction of the tutorials
- implement binder

**Comment by BeardedPlatypus** [comment]
In #264 a binder Dockerfile has been added. This approach leverages the docker support within Binder. Using either `requirements.txt` or an `environments.yml` proved troublesome, especially in resolving the `hydrolib-core` and `meshkernel` packages. Instead the `Dockerfile` copies the `HYDROLIB-core` repository, and then installs it locally through the `pyproject.toml`. This means we do not need to synchronize any dependencies, which simplifies the process.

In order to create a binding for a jupyter notebook, [the mybinder.org website](https://mybinder.org/) can be used:

![image](https://user-images.githubusercontent.com/5596079/176137877-65a8666e-0004-4c0b-92e1-b293fb961e21.png)

Because the Docker image copies the whole repository, we can specify the jupyter notebook path relative to the repository root. The above settings were used to generate the launch button in #264.
