### ISSUE TITLE
type_error when writing OneDFieldModel global values

### ISSUE THREAD

**Issue by Robbertdelange** [Deltares/HYDROLIB-core#278]
**This is probably not a bug, but help is wanted.**

**Describe the bug**
When writing a OneDFieldModel using a dataframe and the OneDFieldModel function, a type_error is returned.

**To Reproduce**
```
df_global = pd.DataFrame(data = [["WaterLevel","m",1.0]],columns = ["quantity","unit","value"])
inifile = OneDFieldModel(global_ = df_global.to_dict('records'))
gives:
```
```
*** pydantic.error_wrappers.ValidationError: 1 validation error for OneDFieldModel
global
  value is not a valid dict (type=type_error.dict)
```

**Expected behavior**
Dataframe is imported into OneDFieldModel. 

**Version info (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. 0.1.5]

**Additional context**
I tried making a dictionary of the value or checking another import of an .ini file, but can't find any differences. Why does the value need to be in a dictionary?
The three inputs for the global_ value are (as far as I know) needed. If I leave out "value", it gives a missing value error.

**Comment by arthurvd** [comment]
Hi @Robbertdelange, your code is almost correct, but needs one change (notice the `[0]`):
```python
        dict = df_global.to_dict("records")
        inifile = OneDFieldModel(global_=dict[0])
```
You can see this by the following: the `OneDFieldModel.global_` is a single object of type OneDFieldGlobal, so the input should not be a list of dict key-values, but rather only that single dict directly.
```python
class OneDFieldModel(INIModel):
    # [..]
    general: OneDFieldGeneral = OneDFieldGeneral()
    global_: Optional[OneDFieldGlobal] = Field(
    # [..]
```
You may have used the .bc file `ForcingModel` from the dataframe tutorial as an example, on:
https://deltares.github.io/HYDROLIB-core/latest/tutorials/dataframe_handling/
There, the full list **is** used for the `forcing` parameter, but that is because the `ForcingModel` has a **list** of `ForcingBase` blocks:
```python
class ForcingModel(INIModel):
# [..]
    general: ForcingGeneral = ForcingGeneral()
    forcing: List[ForcingBase] = []
```
