### ISSUE TITLE
supplying verticalposition to Timeseries should raise an error

### ISSUE THREAD

**Issue by veenstrajelmer** [Deltares/HYDROLIB-core#321]
**Describe the bug**
When supplying verticalposition=VerticalPositionType('ZBed') as an argument to TimeSeries, it is not written to file. This makes sense since Timeseries do not have vertical positions. It would be great if this would be checked upon initialisation (or can it be validated already manually)

When supplying an array instead of list, I get this error:
```
ValidationError: 1 validation error for TimeSeries
    east2_0001 -> datablock -> 0
      value is not a valid list (type=type_error.list)
```

**To Reproduce**
```
ts_one = TimeSeries(name=pli_PolyObject_name_num,
                    verticalposition=VerticalPositionType('ZBed'), 
                    quantityunitpair=[QuantityUnitPair(quantity="time", unit=refdate_str),
                                      QuantityUnitPair(quantity=bcvarname, unit=varunit)],
                    timeinterpolation=TimeInterpolation.linear,
                    datablock=datablock_list, 
                    )
ForcingModel_object.forcing.append(ts_one)
```

**Expected behavior**
Raise exception when not-supported arguments are supplied.

**Version info (please complete the following information):**
 - OS: Windows, Anaconda, Spyder
 - Version: 0.3.0

**Comment by arthurvd** [comment]
Remedy: Possibly the `ForcingBase.Config.extra` could be changed to `Extra.forbid`?

**Comment by arthurvd** [comment]
@veenstrajelmer : the current behavior is:
When you provide attributes that are not known for a particular function type (e.g. `verticalposition` for a **non-3D** `TimeSeries`), then that attribute is silently dropped, so it is not added to the in-memory `TimeSeries` object.
This behavior is intentional, because some users have asked to allow creation of a set of forcing object with a given dataframe as input, where that dataframe also contains several user-specific columns that don't have to appear in the model input files, but the user also doesn't want to first drop these columns.
(Specifically this came up in discussions with @xldeltares who had dataframe input for lateral timeseries on urban manholes.)

Can you understand and accept not changing this behavior?

**Comment by veenstrajelmer** [comment]
This is understandable. The bugfixes for the T3D header already made the initialization a bit more strict so I think there is enough feedback for the user.
