### ISSUE TITLE
Complete support for MDU output keywords

### ISSUE THREAD

**Issue by arthurvd** [Deltares/HYDROLIB-core#525]
**Is your feature request related to a problem? Please describe.**
There are still missing fields for MDU keywords (in the `[Output]` section, in particular several `Wrimap_*` keywords.)
Make this complete.

**Describe the solution you'd like**
Check hydrolib-core support against FM kernel code and User manual.
Bring all three in sync.

**Comment by MRVermeulenDeltares** [comment]
As we understand, the goal for this issue is:
1. Add the keywords described above, with default values.
(The above mentioned default will be used, we assume these are correct when the issue is picked up. Please update them accordingly.)
2. Resolve the default of rstinterval to be in line with the FM kernel.
3. Unknown keywords give a warning and are then dropped. (should this be splitup in a different issue?)

@veenstrajelmer & @rhutten is this correct?

**Comment by tim-vd-aardweg** [comment]
Let's wait until https://github.com/Deltares/HYDROLIB-core/issues/571 is implemented @MRVermeulenDeltares

**Comment by veenstrajelmer** [comment]
With the current main branch, the entire list of keywords in https://github.com/Deltares/HYDROLIB-core/issues/525#issuecomment-1505111924 is now implemented in hydrolib-core
