### ISSUE TITLE
Bumping meshkernel version to latest (v3.0.0)

### ISSUE THREAD

**Issue by ahmad-el-sayed** [Deltares/HYDROLIB-core#569]
**What is the need for this task.**
Currently, HYDROLIB-core uses meshkernelpy 2.0.2, as configured [here](https://github.com/Deltares/HYDROLIB-core/blob/bf75f024e48b515d4cd7c93cd3f997de4fc5b1ef/poetry.lock#L1761C4-L1761C4). A minor version [2.1.0](https://pypi.org/project/meshkernel/2.1.0/) was released last July and version 3.0.0 is planned next week.

**What is the task?**
Is there interest in bumping the version to 3.0.0? 

Benefits:
- improvements in performance
- new features
- bug fixes

These has been API changes. The MeshkernelPy team can gladly assist.

**Comment by veenstrajelmer** [comment]
It is necessary to include the API changes from meshkernel 3.0.0 and use that as a minimal required version.

Fundamentally, these things should be updated:
- [ ] hydrolib-core requires `meshkernel^2.0.0` (so `<3.0.0`), update to `meshkernel^3.0.0` after updates
- [ ] hydrolib-core calls `mk.DeleteMeshOption.ALL_FACE_CIRCUMCENTERS` upon hydrolib-core import, update to new DeleteMeshOption.
- [ ] hydrolib-core calls `mk.MeshKernel(is_geographic=is_geographic)` upon `mdu = hcdfm.FMModel()`, so that command cannot be called.

However, there is more to it I cannot oversee yet. Hydrolib-core currently runs the github testbank with meshkernel 2.0.2 due to poetry.lock. I noticed in a local test (meshkernel 2.1.0) that the deprecated `meshkernel.Mesh2dFactory()` is called in `tests/dflowfm/test_net.py`.

Besides that, there are many functions that use meshkernelpy API's that were changed. A brief overview is available in this issue and it's comments: https://github.com/Deltares/dfm_tools/issues/563
