### ISSUE TITLE
Remove type_enforced dependency

### ISSUE THREAD

**Issue by veenstrajelmer** [Deltares/HYDROLIB-core#584]
**What is the need for this task.**
A fixed version for `type_enfoced` was added to fix the loose version dependency of meshkernel. Remove `type_enforced` dependency again after https://github.com/connor-makowski/type_enforced/issues/24 is fixed or after meshkernel released a version where the version is fixed.

**What is the task?**

**Additional context**

**Comment by connor-makowski** [comment]
Note: This should be fixed in: 

https://github.com/connor-makowski/type_enforced/commit/b58d79f178e8300fe33e70204f4ff9a66aa1fdeb

`type_enforced` note: 1.0.0 and 1.1.0 are both yanked from pypi due to allowed installs in python 3.7 & 3.8. This should have been prevented as these python versions do not have the underlying features needed to support our new type_enforced processes.

To use `python3.7` or `python3.8` you must lock to `type_enforced<=0.0.16`. A fix is in place to function properly in 3.9+ with various restrictions related to python type hints based on exact python version (eg use of `|` for union typing wasn't supported by python until 3.10). 

See the updated docs for more info.
