### ISSUE TITLE
Do not write absolute file paths to file

### ISSUE THREAD

**Issue by priscavdsluis** [Deltares/HYDROLIB-core#96]
I noticed that for example in the mdu file we reference other files with their full file path. 
It might have been caused by issue #42 if this was not previously an issue.

**Comment by BeardedPlatypus** [comment]
# File path architecture

In the current implementation we have several issues in regards to the way we
handle file paths. Currently, when creating a new FileModel we will always 
retrieve a reference to the model when it was first loaded, unless it was 
garbage collected before being retrieved again. This behaviour is in my opinion
incorrect. However, given that this is a functional/behavioural question, I 
believe the full development team should provide input.

As such the first question would be to answer the question:

**How do we expect a model to behave when we create it from a file path.**

The following sections will first provide an overview of the current 
implementation. Then my suggestion for the expected behaviour, and finally
some thoughts on potential solutions / implementations.

## Current Behaviour: Models are read once and cached.

In the current implementation there are two sets of problems:

* The constructor behaviour is unexpected and inconsistent.
* The path resolving is incorrect.

For the first set of problems we will need to choose an approach on how to
deal with reading models from disk, and document it clearly. This might
require a more significant rework of the existing implementation, or merely
some adjustments to ensure the behaviour is consistent. The second set of
problems will need to be addressed regardless of the chosen approach, and
is in line with the problem observed by Prisca which prompted this issue.

### The constructor behaviour is unexpected and inconstistent

In the current implementation we override both the `__new__` and `__init__` 
methods in our `FileModel` class. This allows us to build a cache, which maps
(absolute) paths to the read model and stores them as weak references. This 
approach has merits, in particular it ensures that when loading a single model,
we do not create multiple copies of files that are referenced multiple times 
within the model definition. Furthermore, it speeds up the creation behaviour
as we do not need to read the same file multiple times if we do not change it.

This approach however becomes problematic, once we start modifying the obtained
models. If, in the current approach, a model is created based on path A and
modified, and then a second new model is created also based on path A, the same
modified instance is created. This behaviour I would not expect, instead I 
would expect to have a new copy of the original state on disk. 

Similarly, if we create a model based on path A, then modify the file on disk,
and then reread path A again, we obtain the original model before the changes
on disk. Here I would expect to obtain the state at the time of reading.

Lastly, if we obtain a model based on path A, adjust it and let it go out of
scope and be garbage collected, then reread the path A, we will get the 
original model again, and not the adjust model (as the cache consists of 
weak references). As such the behaviour is not consistent, and dependend on
the garbage collector (which is very bad in my opinion).

This behaviour should at the very least be consistent. Several potential 
solutions are discussed in the potential solution section.

### The path resolving is incorrect

Lastly, there are two additional problems with the current implementation
in regards to how we deal with resolving relative paths:

* Models are now always written with their absolute paths.
* Models do not necessarily have to be relative to their direct parent.

The models now resolve their file path and store it as this resolved absolute
path. The paths are subsequently stored as these absolute paths in their parent
models. This will lead to inconsistencies between read and written models, and
will make the written models non-portable. Instead, the relative paths should
be written again as a relative path, while the caching path should remain an
absolute path. 

Finally, in the `.mdu` file (as well as potentially others)
there is an option to make all file paths of sub-models either relative to
the `.mdu` path parent, or to their direct parent. This, for example creates
an issue when a external forcings file is placed in a different directory than
the `.mdu`. Currently, these paths are always resolved in respect to their
direct parent, however (especially older) model files where this flag is set 
relative to the `.mdu` will not be able to be resolved in this case when the
`.mdu` and external forcings files are not placed in the same directory.

These two problems will need to be addressed, regardless of what behaviour is
chosen when creating new models.

## Expected behaviour

Personally, I would expect that if I create a new instance of a file model, 
with a given a path, I would get a new independent copy of any other files.
This would allow me to for example to create two copies of a model at a 
certain path, and adjust them separately. In the current implementation 
this is not possible. 

## Possible solutions to the behaviour

There are several approaches to improving the current situation, and mitigating
the inconsistencies, depending on the choice in expected behaviour.

If we remain with the current behaviour two potential solutions would be:

* Handle the inconsistent behaviour
* Make the file models immutable, and handle changes by creating copies

If we chose to go with the proposed behaviour, some potential solutions would 
be:

* Only cache file models in a single model load, and rebuild the cache upon a
   later load
* Create a more involved cache utilising a prototype and copying this when 
   requested.
* Introduce a new data reading abstraction layer which handles all this 
   behaviour.

### Handle the inconsistent behaviour

Currently, if we accept the behaviour as is, the main problem besides the 
incorrect path resolving which we need to solve, is the incosistent 
behaviour, primarily in regards to the garbage collector dependent behaviour.
I am unsure what a good approach would be to this, and I also for see
problems when you are changing the actual file path contained in the model
(do we at that point invalidate the cache, or do we still return the same
instance).

### Make the file models immutable, and handle changes by creating copies

If the FileModels are immutable, any adjustment to the model will just 
return a copy. This would solve the problematic behaviour for the most part,
as it is no longer a problem to modify the original. However, this behaviour
is very different from the regular python behaviour when dealing with 
objects, and would most likely feel foreign to consumers of the library, and
could be potentially very resource intensive.

### Only cache file models in a single model load, and rebuild the cache upon a later load

The caching was originally introduced to solve the problem of the same sub model
being read and created multiple times as different instances during a single load.
If we only cache models which are build during a single load, we still solve this
problem, while ensuring we actually read and create a new copy based on the file
contents at the model load. The downside is that we do read files multiple times
potentially, which can become problematic if loading times turn out to be large.

### Create a more involved cache utilising a prototype and copying this when requested

As an alternative on the existing approach, instead of returning the read models 
directly, we would store the read model in the cache, and then create a copy of
this model when it is requested. This would ensure the original data stays intact
while still providing a separate reference. In order to deal with files changing
on disk, we would need to properly invalidate the cache as needed. Furthermore,
a lazy approach to reading, or utilising proxies that point to the original 
until modifications are made, could improve the performance if necessary.

### Introduce a new data reading abstraction layer which handles all behaviour

An alternative to the above approaches is to create a more separate component
that deals with reading. This would involve creating either some classes responsible
for reading the data given a file path and some context, or provide these as class
methods for the file models separate from the actual constructor. This would allow
us to separate this caching from the actual constructor, simplifying the code.

# Next steps

I believe the adjustments to the reading should be done after a choice has been 
made in regards to the creation of (file) models. It might be necessary to 
create some follow-up issues for this if this issue becomes to big.

I believe this should provide ample room for discussion, however if necessary, 
I can further expand on the possible solutions.

**Comment by evetion** [comment]
Thanks for writing it out! So what I'd go for

**Only cache file models in a single model load, and rebuild the cache upon a later load**
This is hopefully an easy adjustment of the current code, keeps the speedup where it matters and generates consistent behaviour.

And with regards to filepaths, we support all options while reading and on writing we do everything relative to the mdu? There might be some tricky exceptions here.

**Comment by priscavdsluis** [comment]
I also prefer the option: "Only cache file models in a single model load, and rebuild the cache upon a later load"
I believe this produces the most logical and reliable behaviour. 
The last option, creating a new abstract layer for reading, is in my opinion the best option to separate the different domains and might make other things easier as well, but I don't think it is the ideal solution for this project.

**Comment by arthurvd** [comment]
## Regarding path resolution:
> Models do not necessarily have to be relative to their direct parent.

Indeed, depending on MDU setting ```PathsRelativeToParent```, which is 0 (off) by default in the kernel, for historical reasons.
However, the recommended behavior **is** ```PathsRelativeToParent = 1```, and it is also the default in the GUIs already.
My recommendation: for serializing, we can hardcode this default. For parsing: add validation rule to MDU that gives an "unsupported error" if PathsRelativeToParent is either missing in the MDU, or set to 0.


## Regarding model caching:
> we do not create multiple copies of files that are referenced multiple times within the model definition

This is typically only useful for multiple references to .bc files from within *.ext or structure.ini files.
All other files are typically referenced only once (or some re-reading overhead is acceptable).

> [..]a second new model is created also based on path A, the same modified instance is created. This behaviour I would not expect, instead I would expect to have a new copy of the original state on disk.

I agree

> Possible solutions to the behaviour

I'm in favour of this option: **Only cache file models in a single model load, and rebuild the cache upon a later load**

**Comment by arthurvd** [comment]
Some end-user ideas about desired functionality:
## save/export
### ```model.export(targetdir)```
should deliver a self-contained set of model input inside the requested targetdir. Possibly a recursive write of the model and all its children, irrespective of which file paths they originally came from. The structure inside the targetdir is a matter of taste, but for now I'd suggest a flat approach for FMModel/RainfallRunoffModel, and in case of a DIMR model, a subdir for each direct child Component.
If original input contains duplicate filenames, originally from different directories, we could improve robustness by renaming them (either with a number postfix in the exported filename, or possibly the original dirname prepended to the exported file name, open to other ideas here).

### ```model.save()```
should save the model and all its child models in their current original filepath.
### Direct save of individual models without any recursing from parents.
For an existing model, earlier loaded, it should be possible to call the save() function on one of its children, without needing any parent save call. Whether or not to recurse into the child model's own children could be made configurable via additional input argument.
Use case:
```
    dimrmodel = DIMR(filepath=test_file)
    assert isinstance(dimrmodel.component[0], FMComponent)
    fmmodel = dimrmodel.component[0]

    struc = Weir(crestlevel=0.0, branchid="aBranchId", chainage=4.2)
    fmmodel.geometry.structurefile[0].structure.append(struc)

    fmmodel.geometry.structurefile[0].save(depth="empty") # <-- example save #1, no descendants

    fmmodel.save(depth="infinity") # <-- example save #2: only FM model (not DIMR), but also *all* its descendants.
```
(I am reusing svn's keywords to define recursion depth, for ease of writing here. See docs on https://svnbook.red-bean.com/en/1.6/svn.advanced.sparsedirs.html )

NOTE: currently a possible workaround is available, as long as the above is not fully supported: if user does a change working dir, prior to saving, it could write individual child models, without needing the parents.

### Save-as functionality 
use case for save-as functionality could be the following:
```
    casedirA = Path("caseA")
    inputfile = "FlowFM.mdu" # mainly contains children with paths relative to this MDU, in several subdirs
    fmmodelA = FMModel(filepath=casedirA / inputfile)

    fmmodelB = fmmodelA # Clone model A into B
    forcingB = ExtModel(filepath="someotherscenario_input.ext")
    fmmodelB.external_forcing.extforcefilenew = forcingB

    fmmodelB.filepath = casedirB / inputfile
    fmmodelB.save() # <-- will save into caseB/, creating the same subdirs under caseB/ as were present under caseA/
```
* ```model.filepath``` vs. ```model.save(targetdir)```
  The Save-as API could contain a targetdir (or better: full target filename), just as I am used to in file dialogs of regular applications. Alternatively, first changing model.filepath first, and then calling ```save()``` is also acceptable, but I do not why that is so much better/cleaner.
  In either case, I understand that absolute file paths (or at least parents base dir) must be changed in all child models. In the ```save(targetdir)``` approach, this could be automatically called recursively by the save function itself, prior to the actual save. In the ```model.filepath``` approach, either the user must call such an recursive-updater function, or some trigger must be launched?
* Absolute paths in children
  If any child model was originally referenced via absolute file paths in any parent model of fmmodelA, then also under fmmodelB, that reference remains an absolute path.
* Relative file paths pointing above highest root model dir
  If any child model under fmmodelA is referenced via a relative file path that lies above the dir of fmmodelA itself, then in the fmmodelB that relative path is kept the same (so consistent with all other relative paths), but this then also means, that that part of the input does not need to have directories created (as they should already exist).
  The call to fmmodelB.save(depth="infinity") with full recursion should save all child models, so also the ones outside of fmmodelA/B's own dirtree. It is the responsibility of the user to think about whether such shared directories are useful for him/her or not.

**Comment by BeardedPlatypus** [comment]
# Summary of the current design decisions

## Functional choices

* Refactor the `save` api to `save(filepath=None, recurse=False)`
    - If a filepath is provided, the internal `filepath` will be set before saving.
    - If `recurse` is set to `False`, the default, only this model is saved.
    - If `recurse` is set to `True`, all of the sub models will be stored as well. Any relative paths will be resolved relative to this model's `filepath`.
* A new `save_location -> Path` read-only property is introduced. This property returns the absolute path where the file is saved if `save()` would be called.
* When a model is initialised, the `save_location` corresponds with where the file was read.
* A new `synchronise_filepaths` is introduced, which will update the save locations of all children, respective to this `FileModel`. This will ensure `save_location` is correct in child models relative to the model it was called on.
* When saving a model recursively (`save(recurse=True)`), the save_location is updated in the same way as `synchronize_filepaths`
* If a `filepath` is absolute, it will always be equal to the `save_location`, regardless of the internal state.
* If a user changes an absolute `filepath` to a `relative_path`, the `save_location` will be updated to `prev_state.filepath.parent / current_state.filepath`.

These changes have a few consequences for the user, which should be clearly documented. In particular:

* Before saving a sub-model, it is recommended to call `synchronize_filepaths`, to ensure the files are saved in the expected location
* Recursively saving sub-models of an `FMModel` which have a relative path and with `pathsRelativeToParent` set to false will result in incorrect paths. However given that setting this to `False` is not encouraged, this should not occur often.

## Architectural design

In order to support the functional behaviour described above, we will add a new (private) field to the `FileModel`. This field, `_absolute_anchor_path`, contains the directory to which the `filepath` should be resolved if it is relative. This field will be set upon initialising a field from a file, when saving, and when calling the `synchronize_filepaths`. Each of these functions will have access to a `FilePathResolver` and as such can determine the absolute path.

This would require the constructor and the `_save` logic to be extended with a `self._absolute_anchor_path` assignment.

### `save_location`

The `save_location` property can then be implemented as follows:

```python
@property
def with_default(value, default):
    if value is not None:
        return value
    else:
        return default

def save_location(self) -> Path:
    relative_anchor = with_default(self.absolute_anchor_path, Path.cwd())
    filepath = with_default(self.filepath, self.generate_name())

    if filepath.is_absolute:
        return filepath

    return relative_anchor / filepath
```

This should work correctly with most changes in filepath:

* Relative to relative filepath: relative path will still be resolved with respect to the original anchor
* Absolute to absolute filepath: the new absolute path will be returned
* Relative to absolute filepath: the new absolute path will be returned

The potentially unexpected behaviour is when we switch from absolute to relative. In this case it will be set to wherever the last synchronisation was pointing to. This needs to be clearly documented.

### `synchronize_filepaths`

The `synchronize_filepaths` can be implemented similarly to the implementation of save, but not actually executing the serialization to disk. As such it should traverse through the model hierarchy, and set the `_absolute_anchor_path` equal to the current direct parent stored in the `FilePathResolver`.

### `save`

The `save` call should act as a facade, and the actual implementation of the different behaviours should be split into separate functions. An example would be:

```python
def save(filepath: Optional[Path] = None, recurse: bool = False) -> None:
    if filepath is not None:
        self.filepath = filepath

    if recurse:
        self._save_tree()
    else:
        self._save_instance()
```
